### ISSUE TITLE
Enable Progressive Web App

### ISSUE THREAD

**Issue by scott181182** [cesmii/OEE-SMIP-App#44]

**Comment by scott181182** [comment]
We'll need an icon (recommend 512x512 PNG), and any manifest/metadata from @jwise-mfg

**Comment by jwise-mfg** [comment]
![OEE](https://github.com/cesmii/OEE-SMIP-App/assets/57234292/b6f99e76-cd03-4daf-8bcd-eed8a00930f9)

**Comment by jwise-mfg** [comment]
![CESMII_Logo_NoTag_RGB](https://github.com/cesmii/OEE-SMIP-App/assets/57234292/b57a9e89-6904-409c-af59-217d326748ed)

**Comment by jwise-mfg** [comment]
[manifest.json](https://github.com/user-attachments/files/15657485/manifest.json)

**Comment by jwise-mfg** [comment]
Gauge with "OEE" and the CESMII gear is the general idea. We have a marketing person who can do a better treatment of this icon later.

**Comment by jwise-mfg** [comment]
@scott181182 can you replace the favicon too? Looks like its showing just a generic icon --maybe from the framework you used?

**Comment by scott181182** [comment]
@jwise-mfg will do!
